# Container that runs HDFS NameNode and DataNode services

nginx-tcpflow:
 image: nginx-tcpflow
 hostname: nginx-tcpflow
 links:
   - kafka:kafka
 ports:
   - "80:80"
 volumes:
   - /etc/localtime:/etc/localtime

zookeeper:
 image: zookeeper:latest
 hostname: zookeeper
 ports:
   - "2181"
 volumes:
   - /etc/localtime:/etc/localtime

kafka:
 image: wurstmeister/kafka:latest
 hostname: kafka
 ports:
   - "9092"
   - "6667"
 links:
   - zookeeper:zookeeper
 environment:
  - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  - KAFKA_ADVERTISED_HOST_NAME=kafka
  - KAFKA_ADVERTISED_PORT=9092
 volumes:
   - /etc/localtime:/etc/localtime

hdfs-namenode:
 image: hdfs-namenode
 hostname: hdfs-namenode-host
 ports:
   # HDFS port
   - "9000:9000"
   # HDFS NameNode WebUI
   - "50070:50070"
 # Adjust according to the resources available on host machine
 cpu_shares: 3000
 mem_limit: 2g
 links:
   - kafka:kafka

# Container that runs HDFS DataNode service
hdfs-datanode:
 image: hdfs-datanode
 hostname: hdfs-datanode-host
 links:
   - hdfs-namenode
 environment:
   # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
   - NAMENODE_HOSTNAME=hdfs-namenode-host
 # Adjust according to the resources available on host machine
 cpu_shares: 3000
 mem_limit: 2g
 volumes:
   - /etc/localtime:/etc/localtime

# Container that runs Spark Master and Worker services
spark-master:
 image: spark-master
 hostname: spark-master-host
 links:
   - hdfs-namenode
 ports:
   # Spark master WebUI port
   - "8080:8080"
   # Spark master job submission port
   - "7077:7077"
 environment:
   # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
   - NAMENODE_HOSTNAME=hdfs-namenode-host
 # Adjust according to the resources available on host machine
 cpu_shares: 3000
 mem_limit: 2g
 volumes:
   - /etc/localtime:/etc/localtime

# Container that runs Spark Worker service
spark-slave:
 image: spark-slave
 hostname: spark-slave-host
 links:
   - hdfs-namenode
   - spark-master
 environment:
   # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
   - NAMENODE_HOSTNAME=hdfs-namenode-host
   # MASTER_HOSTNAME is the hostname of the container running Spark master service
   - MASTER_HOSTNAME=spark-master-host
 # Adjust according to the resources available on host machine
 cpu_shares: 3000
 mem_limit: 2g
 volumes:
   - /etc/localtime:/etc/localtime
